mutation{
  createNewStudent(
    newStudent:{
      Firstname:"manan",
      Lastname:"dhameliya",
      Email:"manan@gmail.com",
      Password:"manan",
      Class:"60b489f523a1ea21186860a8",
   
    }
  ){
    id
    Firstname
    Lastname
    Email
    Password
    Class
    role
    isActive
  }
}


mutation{
  deleteStudent(id:"60b4c9dc1e061c198c2b7ae7"){
    id
    message
    success
  }
}


mutation{
  updateStudent(
    updatedPost:{
      Firstname:"conor",
      Lastname:"mcgrgor",
      Email:"conor@gmail.com",
      Password:"123"
    }
    id:"60b4c9a71e061c198c2b7ae5"
  ){
    id
    Firstname
    Lastname
    Email
    Password
    Class
    role
    isActive
  }
}


query GET_SINGLE_STUDENT($id:ID!){
getSingleStudent(id:$id){
  id
  Firstname
  Lastname
  Email
  Password
  Class
  enrno
  role{
    id
    Rolename
    
  }
  createdAt   
  updatedAt  
}  
}


query GET_ALL_STUDENT {
   getAllStudent     {
   id
    Firstname
    Lastname
    Email
    enrno
    Class
    role{
    id
    Rolename
    createdBy
    updatedBy
    createdAt
    updatedAt
    isActive
  }
    
  }
}


