export const USER_EVENTS = {
    ROLE_CREATED: 'ROLE_CREATED',
    ROLE_DELETED: 'ROLE_DELETED',
    ROLE_UPDATED:'ROLE_UPDATED',

    CLASS_CREATED: 'CLASS_CREATED',
    CLASS_DELETED: 'CLASS_DELETED',
    CLASS_UPDATED:'CLASS_UPDATED',

    SUBJECT_CREATED: 'SUBJECT_CREATED',
    SUBJECT_DELETED: 'SUBJECT_DELETED',
    SUBJECT_UPDATED:'SUBJECT_UPDATED',

    FACULTY_CREATED: 'FACULTY_CREATED',
    FACULTY_DELETED: 'FACULTY_DELETED',
    FACULTY_UPDATED:'FACULTY_UPDATED',

    STUDENT_CREATED: 'STUDENT_CREATED',
    STUDENT_DELETED: 'STUDENT_DELETED',
    STUDENT_UPDATED:'STUDENT_UPDATED',

    ATTENDANCE_CREATED:'ATTENDANCE_CREATED',
    ATTENDANCE_UPDATED:'ATTENDANCE_UPDATED',

    BOOK_CREATED:'BOOK_CREATED',
    BOOK_DELETED:'BOOK_DELETED',
    BOOK_UPDATED:'BOOK_UPDATED',

    BOOKISSUER_CREATED:'BOOKISSUER_CREATED',
    BOOKISSUER_DELETED:'BOOKISSUER_DELETED',
    BOOKISSUER_UPDATED:'BOOKISSUER_UPDATED',
    
    RESULT_CREATED:'RESULT_CREATED',
    RESULT_UPDATED:'RESULT_UPDATED',
}


  



